CREATE DATABASE IF NOT EXISTS budgit_db;

CREATE TABLE IF NOT EXISTS budgit_db.BUDGET_TABLE(
	BUDGET_ID INT AUTO_INCREMENT,
	LEISURE INT, 
	SUPERMARKET INT,
	TRAVEL INT,
	FOOD_DRINK INT,
	ELECTRONICS_MEDIA INT,
	OTHER INT

	PRIMARY KEY(BUDGET_ID)
);

CREATE TABLE IF NOT EXISTS budgit_db.PET_TYPE_TABLE(
	PET_TYPE_ID INT AUTO_INCREMENT,
	PET_TYPE_NAME VARCHAR(50),
	PET_IMG_URL VARCHAR(255)

	PRIMARY KEY(PET_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS budgit_db.ITEM_TYPE_TABLE(
	ITEM_TYPE_ID INT AUTO_INCREMENT,
	PRICE INT,
	HAPPINESS_BOOST INT,
	ITEM_IMG_URL VARCHAR(255)

	PRIMARY KEY(ITEM_TYPE_ID) 
);

CREATE TABLE IF NOT budgit_db.EXISTS PET_TABLE(
	PET_ID INT AUTO_INCREMENT,
	PET_TYPE_ID INT,
	HAPPINESS_SCORE INT 

	PRIMARY KEY(PET_ID)
	FOREIGN KEY(PET_TYPE_ID) REFERENCES PET_TYPE_TABLE(PET_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS budgit_db.USER_TABLE(
	USER_ID INT AUTO_INCREMENT,
	USER_NAME VARCHAR(50),
	PET_ID INT,
	MONEY_AMOUNT INT,
	BUDGET_ID INT,
	MONEY_TO_AWARD INT
	
	PRIMARY KEY(USER_ID),
	FOREIGN KEY(PET_ID) REFERENCES PET_TABLE(PET_ID)
);

CREATE TABLE IF NOT EXISTS budgit_db.ITEM_USER_TABLE(
	USER_ID INT,
	ITEM_TYPE_ID INT,
	QUANTITY INT 

	PRIMARY KEY(USER_ID, ITEM_TYPE_ID)
	FOREIGN KEY(USER_ID) REFERENCES USER_TABLE(USER_ID)
	FOREIGN KEY (ITEM_TYPE_ID) REFERENCES ITEM_TYPE_TABLE(ITEM_TYPE_ID)
);


GRANT ALL PRIVILEGES ON budgit_db.* TO 'flask_user'@'localhost';









