CREATE DATABASE IF NOT EXISTS budgit_db;

CREATE TABLE IF NOT EXISTS budgit_db.BUDGET_TABLE(
	BUDGET_ID INT NOT NULL AUTO_INCREMENT,
	LEISURE INT NOT NULL, 
	SUPERMARKET INT NOT NULL,
	TRAVEL INT NOT NULL,
	FOOD_DRINK INT NOT NULL,
	ELECTRONICS_MEDIA INT NOT NULL,
	OTHER INT NOT NULL,

	PRIMARY KEY(BUDGET_ID)
);

CREATE TABLE IF NOT EXISTS budgit_db.PET_TYPE_TABLE(
	PET_TYPE_ID INT NOT NULL AUTO_INCREMENT,
	PET_TYPE_NAME VARCHAR(50) NOT NULL,
	PET_IMG_URL VARCHAR(255) NOT NULL,

	PRIMARY KEY(PET_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS budgit_db.ITEM_TYPE_TABLE(
	ITEM_TYPE_ID INT NOT NULL AUTO_INCREMENT,
	PRICE INT NOT NULL,
	HAPPINESS_BOOST INT NOT NULL,
	ITEM_IMG_URL VARCHAR(255) NOT NULL,

	PRIMARY KEY(ITEM_TYPE_ID) 
);

CREATE TABLE IF NOT budgit_db.EXISTS PET_TABLE(
	PET_ID INT NOT NULLAUTO_INCREMENT,
	PET_TYPE_ID NOT NULL INT,
	HAPPINESS_SCORE NOT NULL INT, 

	PRIMARY KEY(PET_ID),
	FOREIGN KEY(PET_TYPE_ID) REFERENCES PET_TYPE_TABLE(PET_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS budgit_db.USER_TABLE(
	USER_ID INT NOT NULL AUTO_INCREMENT,
	USER_NAME NOT NULL VARCHAR(50),
	PET_ID NOT NULL INT,
	MONEY_AMOUNT NOT NULL INT,
	BUDGET_ID NOT NULL INT,
	MONEY_TO_AWARD NOT NULL INT,
	
	PRIMARY KEY(USER_ID),
	FOREIGN KEY(PET_ID) REFERENCES PET_TABLE(PET_ID)
);

CREATE TABLE IF NOT EXISTS budgit_db.ITEM_USER_TABLE(
	USER_ID NOT NULL INT,
	ITEM_TYPE_ID NOT NULL INT,
	QUANTITY NOT NULL INT, 

	PRIMARY KEY(USER_ID, ITEM_TYPE_ID),
	FOREIGN KEY(USER_ID) REFERENCES USER_TABLE(USER_ID),
	FOREIGN KEY (ITEM_TYPE_ID) REFERENCES ITEM_TYPE_TABLE(ITEM_TYPE_ID)
);


GRANT ALL PRIVILEGES ON budgit_db.* TO 'flask_user'@'localhost';









